name: CI

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVELOCITY_INJECTION_ENABLED: "false"
      AIFB_POSTGRES_URL: ${{ secrets.AIFB_POSTGRES_URL }}
      AIFB_POSTGRES_USER: ${{ secrets.AIFB_POSTGRES_USER }}
      AIFB_POSTGRES_PASSWORD: ${{ secrets.AIFB_POSTGRES_PASSWORD }}
      AIFB_POSTGRES_SSL_CERT_BASE64: ${{ secrets.AIFB_POSTGRES_SSL_CERT_BASE64 }}
    # Testcontainers is used for DB ITs; service postgres is not required
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          develocity-injection: false

      - name: Build (without DB ITs)
        run: ./gradlew clean assemble check -x :features:db:test --no-daemon --stacktrace --info

      - name: Prepare SSL certificate (if provided)
        if: ${{ env.AIFB_POSTGRES_SSL_CERT_BASE64 != '' }}
        run: |
          mkdir -p configs/ssl
          # Try to decode as base64; if it fails, treat input as raw PEM
          if echo "${{ env.AIFB_POSTGRES_SSL_CERT_BASE64 }}" | base64 -d > configs/ssl/yandex-cloud-root-ca.pem 2>/dev/null; then
            echo "Decoded base64 SSL cert to configs/ssl/yandex-cloud-root-ca.pem"
          else
            printf "%s" "${{ env.AIFB_POSTGRES_SSL_CERT_BASE64 }}" > configs/ssl/yandex-cloud-root-ca.pem
            echo "Wrote raw PEM SSL cert to configs/ssl/yandex-cloud-root-ca.pem"
          fi

      # DB ITs requiring Testcontainers are disabled; run regular unit tests only

      - name: Run Detekt
        run: ./gradlew detekt --no-daemon || true

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            **/build/reports/**
            **/build/test-results/**

