name: CI

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: aifb
          POSTGRES_USER: aifb
          POSTGRES_PASSWORD: aifb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U aifb -d aifb" --health-interval 10s --health-timeout 5s --health-retries 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build (no tests for now)
        run: ./gradlew clean build -x test --no-daemon

      - name: Run unit tests
        run: ./gradlew test --no-daemon

      - name: Run DB integration tests (features:db)
        env:
          AIFB_POSTGRES_URL: jdbc:postgresql://localhost:5432/aifb
          AIFB_POSTGRES_USER: aifb
          AIFB_POSTGRES_PASSWORD: aifb
        run: ./gradlew :features:db:test --no-daemon

      - name: Run Detekt
        run: ./gradlew detekt --no-daemon || true

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            **/build/reports/**
            **/build/test-results/**

